version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  app:
    image: node:16
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: npm run start
